# To get started with Dependabot version updates, specify package ecosystems and where manifests are located.
# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions" # update GitHub Actions workflows
    directory: "/.github/workflows" # Location of workflow files
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # update npm dependencies (change or remove if not applicable)
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly"
